
package com.bv.provider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Helloworld", targetNamespace = "http://provider.bv.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Helloworld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getdata", targetNamespace = "http://provider.bv.com/", className = "com.bv.provider.Getdata")
    @ResponseWrapper(localName = "getdataResponse", targetNamespace = "http://provider.bv.com/", className = "com.bv.provider.GetdataResponse")
    @Action(input = "http://provider.bv.com/Helloworld/getdataRequest", output = "http://provider.bv.com/Helloworld/getdataResponse")
    public String getdata(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
